train_dataset:
  name: mini
  args:
    tail_path: mini-imagenet/train
    transform_list: 
      - RandomResizedCrop
      - RandomHorizontalFlip
      - ToTensor
      - Normalize
    image_size: 80
    
val_dataset:
  name: mini
  args:
    tail_path: mini-imagenet/train
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 80

model:
  name: classifier
  args:
    encoder:
      name: resnet12
      args: {}
    cls_num: 64
      
optimizer:
  name: SGD
  args:
    lr: 0.1
    weight_decay: 5.e-4
    
lr_scheduler:
  name: MultiStepLR
  args:
    milestones:
      - 90
    
max_epoch: 100
batch_size: 128